export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const LOAD_FARMS_SUCCESS = 'LOAD_FARMS_SUCCESS';
export const CREATE_FARM_SUCCESS = 'CREATE_SOMETHING_SUCCESS';
export const UPDATE_FARM_SUCCESS = 'UPDATE_SOMETHING_SUCCESS';
export const SELECT_FARM_SUCCESS = 'SELECT_SOMETHING_SUCCESS';

export const SELECT_FARM_ERROR = 'SELECT_ROUTE_ERROR';
